# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sandbox 
email: mjjcha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I come to play by myself.
  Don't be gross, that's not what I meant.
  Or maybe it is. I don't know.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  mjjcha

# Build settings
markdown: kramdown
